### ISSUE TITLE
Need input on range validation

### ISSUE THREAD

**Issue by dyu-satishp7** [kriswiner/STHS34PF80#3]
Hi Kriswiner,

First, thank you for creating this. It is leading to solve many use cases. We are in process of creating one such use case for energy savings.

We are currently evaluating STHS34PF80, but we are getting the range limited to 1 meter. Is there any thing we need to keep in mind with respect to this sensor. What is your setup and validation data on this sensor ? It would be great if you can share some inputs on this as we are currently stuck with the limited range.

--
satish

**Comment by kriswiner** [comment]
According to the datasheet
<https://www.st.com/resource/en/datasheet/sths34pf80.pdf>, you should be
able to detect objects 4 meters away if they are big enough (like humans,
for example) without a lens. My working distance was about a meter and I
did not test for larger range. Contact ST for the best information.

**Comment by dyu-satishp7** [comment]
@kriswiner  - Thanks for the reply. Somehow we have tried following their algorithms, but we are not getting more than 2 meter range. Will follow up with them.

--
satish
